version: '3.8'

services:

  nginx:
    image: nginx:latest
    container_name: meu_nginx
    ports:
      - "8080:80"  
    volumes:
      - ./src:/github/startup_connect/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
db:
    image: mysql:8.0
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: startup_connect
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:github/startup_connect/sql/

volumes:
  mysql_data: