version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginxStartup
    ports:
      - "8080:80"  
    volumes:
      - ./src:/github/startup_connect/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    build: .
    container_name: phpStartup
    volumes:
      - ./src:/github/startup_connect/
    expose:
      - "9000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: startup_connect
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql/

volumes:
  mysql_data:
